# Task-6 (Numpy)
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [8]:
import numpy as np 

Arrays

In [11]:
A = input('Enter space-separated numbers : ').strip().split(' ')
A = np.array(A)
Reversed_A = A[::-1]
print(Reversed_A)

Enter space-separated numbers : 1 2 3
['3' '2' '1']


Shape and Reshape

In [22]:
A = np.array(input('Enter space-separated numbers : ').split(),int)
print(A.shape)
A = A.reshape(3,3)
print(A)

Enter space-separated numbers : 1 2 3 4 5 6 7 8 9
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Transpose and Flatten

In [25]:
# N Rows and M Columns
N,M = map(int, input('Enter space-separeted values of N and M : ').split())
A = np.array([input('Enter space-separated elements : ').split() for _ in range(N)],int) # Enter elements for each row. 
print(A.transpose())
print(A.flatten())

Enter space-separeted values of N and M : 3 3
Enter space-separated elements : 2 4 5
Enter space-separated elements : 3 5 6
Enter space-separated elements : 2 4 5
[[2 3 2]
 [4 5 4]
 [5 6 5]]
[2 4 5 3 5 6 2 4 5]


Concatenate

In [33]:
# N and M are rows and P is the column
P,N,M = map(int, input('Enter space-separeted values of N and M and P : ').split())
A = np.array([input('Enter space-separated elements : ').split() for _ in range(P)],int)
B = np.array([input('Enter space-separated elements : ').split() for _ in range(N)],int)
C = np.concatenate((A,B),axis = 0)
print(C)

Enter space-separeted values of P and M and P : 4 3 2
Enter space-separated elements : 1 2
Enter space-separated elements : 1 2
Enter space-separated elements : 1 2
Enter space-separated elements : 1 2
Enter space-separated elements : 4 3
Enter space-separated elements : 4 3
Enter space-separated elements : 4 3
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [4 3]
 [4 3]
 [4 3]]


Zeros and Ones

In [36]:
A = tuple(map(int, input('Enter space-separeted values of X and Y and Z : ').split()))
print(np.zeros(A, int))
print(np.ones(A, int))

Enter space-separeted values of X and Y and Z : 3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Eye and Identity

In [43]:
N,M = map(int, input('Enter space-separeted values of N and M : ').split())
print(np.eye(N,M))

Enter space-separeted values of N and M : 3 2
[[1. 0.]
 [0. 1.]
 [0. 0.]]


Array Mathematics

In [49]:
N,M = map(int, input('Enter space-separeted values of M and N : ').split()) # N lines and M integer/line
A = np.array([list(map(int, input('Enter space-separated elements : ').split())) for n in range(N)])
B = np.array([list(map(int, input('Enter space-separated elements : ').split())) for n in range(N)])

print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))
print(np.mod(A,B))
print(np.power(A,B))

Enter space-separeted values of M and N : 1 4
Enter space-separated elements : 1 2 3 4
Enter space-separated elements : 5 6 7 8 
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0.2        0.33333333 0.42857143 0.5       ]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


Floor, Ceil and Rint

In [56]:
A = np.array([list(map(float, input('Enter space-separated elements : ').split()))])
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

Enter space-separated elements : 1.21 2.54 3.65 4.22 9.32
[[ 2.  3.  4.  5. 10.]]
[[1. 2. 3. 4. 9.]]
[[1. 3. 4. 4. 9.]]


Sum and Prod

In [58]:
N, M = map(int, input('Enter space-separated values of N and M : ').split()) # N lines and M integers/line
A = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
Sum = np.sum(A,axis = 0)
Prod = np.prod(Sum,axis = 0)
print(Prod)

Enter space-separated values of N and M : 2 2
1 2
3 4
24


Min and Max

In [59]:
N, M = map(int, input('Enter space-separated values of N and M : ').split())
A = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
Min = np.min(A,axis = 1)
print(np.max(Min))

Enter space-separated values of N and M : 4 2
2 5
3 7
1 3
4 0
3


Mean, Var and Std

In [63]:
N, M = map(int, input('Enter space-separated values of N and M : ').split())
A = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
print(np.mean(A,axis = 1))
print(np.var(A,axis = 0))
np.set_printoptions(legacy='1.13')
print(np.std(A))

Enter space-separated values of N and M : 2 2
Enter your numbers : 1 2
Enter your numbers : 3 4
[1.5 3.5]
[1. 1.]
1.11803398875


Dot and Cross

In [66]:
N = int(input('Enter space-separeted values of N : ')) # N lines and M integer/line
A = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
B = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
print(np.dot(A,B))

Enter space-separeted values of N : 2
Enter your numbers : 1 2
Enter your numbers : 3 4
Enter your numbers : 1 2
Enter your numbers : 3 4
[[ 7 10]
 [15 22]]


Inner and Outer

In [68]:
A = np.array(input('Enter your numbers : ').split(),int)
B = np.array(input('Enter your numbers : ').split(),int)
print(np.inner(A,B))
print(np.outer(A,B))

Enter your numbers : 0 1
Enter your numbers : 2 3
3
[[0 0]
 [2 3]]


Polynomials

In [70]:
# Coefficients
A,B,C = map(float, input('Enter space-separated values of Coefficients : ').split())
X = int(input('Enter value of X  : ')) 
print(np.polyval([A,B,C],X))

Enter space-separated values of Coefficients : 1.1 2 3
Enter value of X  : 0
3.0


Linear Algebra

In [74]:
N = int(input('Enter value of N  : ')) 
A = np.array([input('Enter your numbers : ').split() for _ in range(N)],float)
# Output needs to be round to 2 decimal points
print(round(np.linalg.det(A),2))

Enter value of N  : 2
Enter your numbers : 1.1 1.1
Enter your numbers : 1.1 1.1
0.0
